name: generate animation

on:
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: leereilly
          svg_out_path: dist/github-contribution-grid-snake.svg
